version: '3.4'

services:
  api:
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4050:4050
    env_file:
      - .env
    links: 
      - mongo
      - mysql
    depends_on: 
      - mysql
      - mongo
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    networks: 
      - sail
    restart: always
    command: npm run migration && npm run dev
