version: '3.4'

services:
  test_api:
    build: .
    environment:
      NODE_ENV: test
    ports:
      - 4200:4051
    env_file:
      - .env.integration
    links:
      - mysql
      - mongo
    depends_on:
      - mysql
      - mongo
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - sail
    container_name: test_api
    command: npm run migration && npm run dev
  api_test:
    image: server_test_api:latest
    environment:
      NODE_ENV: test
    env_file:
      - .env.integration
    depends_on:
      - mysql
      - test_api
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - sail
    command: npm run test