version: '3.4'

services:
  api:
    build: .
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on: 
      - mongo
    links: 
      - mongo
    ports:
      - 4050:4050
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    networks: 
      - sail
    restart: always
    command: npm run dev
